name: .NET

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup NUKE
      run: dotnet tool install Nuke.GlobalTool --global
    - name: Setup Git
      run: |
        git config --global user.email "31213871+UltzLtd@users.noreply.github.com"
        git config --global user.name "Ultz"
    - name: Full Run
      run: nuke fullrun --nuget-api-key ${{ secrets.NUGET_TOKEN }} --configuration Release
